<a href="https://colab.research.google.com/github/NikhilKanamarla/Practice/blob/master/PyTorchPractice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
x = torch.empty(1)
z = torch.zeros(2,3)
print(x)
print(z)
#an array of data which runs well on the GPU
x = torch.Tensor([5,3])
print (x * x)
y = torch.zeros([2,5])
print(y)
#check size of tensor
print(y.shape)
#random initalization
y = torch.rand(2,5)
print(y)
#reshape tensor to fit input shape of neural network
y = y.view([1,10])
print(y.shape)

tensor([1.0112e-35])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([25.,  9.])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([2, 5])
tensor([[0.5629, 0.3775, 0.9956, 0.3239, 0.7829],
        [0.9785, 0.7673, 0.3446, 0.5217, 0.3014]])
torch.Size([1, 10])
